var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-38662434-1"]);_gaq.push(["_trackPageview"]);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="https://ssl.google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();var selectedOptions,OPTIONAL_KEYWORD="{%%Optional-Keyword%%}",keywordsSeparator,isCookieSupported=$.cookies.test();
$(function(){var a=$('[data-toggle="tooltip"]'),b=$(".navbar-fixed-top").find(".nav-item-help-tips"),e=function(c){0==c?(b.removeClass("active"),$("#main-content").fadeTo(200,1),a.tooltip("hide")):(b.addClass("active"),$("#main-content").fadeTo(200,.5),a.tooltip("show"))};b.on("click",function(a){e(!$(this).hasClass("active"))});$(".navbar-fixed-top").on("click",'[data-toggle="tab"]',function(a){e(!1)});var c=$("#results-box"),d,h;$(window).on("scroll",function(){d=Math.max(0,$(this).scrollTop());
h=$(".tab-pane.active").height()-c.height();d<h&&c.css("top",d)});c.on("click",".save-results",function(a){a.preventDefault();saveResults();saveCookies()});c.on("click",".close",function(a){a.preventDefault();$(this).parent().remove();saveCookies()});c.on("click",".result-item",function(a){a.preventDefault();a.preventDefault();showResult($(this).data().keywords)});$("body").on("focus",".keywords-compiled",function(a){var b=$(this);b.select();b.mouseup(function(){b.unbind("mouseup");return!1})});$("#wrapper .btn").click(function(a){_gaq.push(["_trackEvent",
"Tool",$(this).attr("rel"),$(this).hasClass("active").toString()]);setTimeout(function(){wrapKeywords()},50)});$("#wrapper .keywords-input").on("input propertychange",function(){wrapKeywords()});$("#typoer .btn").click(function(a){_gaq.push(["_trackEvent","Tool",$(this).attr("rel"),$(this).hasClass("active").toString()]);setTimeout(function(){typoKeywords()},50)});$("#typoer .keywords-input").on("input propertychange",function(){typoKeywords()});$("#mixer").on("click",".generate-multi-list",function(a){setTimeout(function(){mixKeywordsLists()},
50)});$("#mixer").on("click",".tools-separate label",function(a){"custom_separator"==$(this).attr("rel")?$("#custom-separator").slideDown(200,function(){$(this).focus()}):$("#custom-separator").slideUp(100)});loadCookies()});function saveCookies(){if(isCookieSupported){var a={results:[]};$("#results-box").find(".result-item").each(function(b,e){a.results.push($(this).data().keywords)});$.cookies.set("data",a)}}
function loadCookies(){if(isCookieSupported){var a=$.cookies.get("data");a&&a.results&&$.each(a.results,function(a,e){saveResults(e)})}}function showResult(a){if(a){var b=$(".tab-pane.active").find(".keywords-input").first();b.val(a.join("\n"));b.trigger("propertychange")}}
function saveResults(a){a=a?a:$(".tab-pane.active").find(".keywords-compiled").val().split("\n");var b=$("#results-box").find(".results-list"),e=$("<span>",{"class":"badge keywords-count"}).html(a.length),c=$("<button>",{type:"button","class":"close"}).html("&times;"),d=$("<span>",{"class":"keywords-preview"}).html(a.join(" ").substr(0,20)+"...");a=utilRemoveEmptyKeywords(a);a=$("<li>",{"class":"list-group-item result-item"}).data({keywords:a});a.append(c).append(e).append(d);b.append(a)}
function selectedOption(a){return-1==$.inArray(a,selectedOptions)?!1:!0}
function mixKeywordsLists(){var a=$("#mixer .keywords-input"),b=[],e,c=[];$("#mixer").find(".tune-list").find(".btn.active").each(function(a,b){c.push($(this).attr("rel"))});a.each(function(a,d){d=$(d);e=d.val();if(0==e.length)return!0;var k=[];selectedOptions=c.concat([]);d.parents(".input").first().find(".btn.active").each(function(a,b){selectedOptions.push($(this).attr("rel"))});e=getModifiedKeywords(e);k=selectedOption("permute")?permuteWords(e):[].concat(e);if(selectedOption("optional")){var f=
[];$.each(k,function(a,b){f.push(b);f.push(OPTIONAL_KEYWORD)});k=f}b.push(k)});selectedOptions=c.concat([]);b=selectedOption("permute-lists")?permute(b):[b];keywordsSeparator=$("#mixer").find(".tools-separate").find(".btn.active").attr("rel");"custom_separator"==keywordsSeparator&&(keywordsSeparator=$("#custom-separator").val());var d=[];$.each(b,function(a,b){d=d.concat(getMixedKeywordsLists(b))});a=keywordsSeparator.replace(".","\\.");replaceOptionalRegExp=new RegExp("("+a+OPTIONAL_KEYWORD+"|"+
OPTIONAL_KEYWORD+a+"|"+OPTIONAL_KEYWORD+")","gi");keywordsTechSeparator="{%%Keyword_separator%%}";d=d.join(keywordsTechSeparator);d=d.replace(replaceOptionalRegExp,"");d=d.replace(/^\s\s*/,"").replace(/\s\s*$/,"");d=d.replace(/\s{2,}/g," ");d=d.split(keywordsTechSeparator);d=utilRemoveEmptyKeywords(d);selectedOption("duplicates")&&(d=utilRemoveDuplicates(d));$("#mixer .input .summary").html(e.length+" Keywords in Total");$("#mixer .output .summary").html(d.length+" Keywords in Total");$("#mixer .keywords-compiled").val(d.join("\n"))}
function getMixedKeywordsLists(a,b){"undefined"===typeof b&&(b="");var e,c=[];1<a.length?(e=a.shift(),$.each(e,function(d,e){c=c.concat(getMixedKeywordsLists(a.concat([]),b+(""==e?"":e+keywordsSeparator)))})):(e=a[0],$.each(e,function(a,e){c.push(b+e)}));return c}
function wrapKeywords(){var a=$("#wrapper .keywords-input").val(),b=[];selectedOptions=[];$("#wrapper .btn.active").each(function(){selectedOptions.push($(this).attr("rel"))});_gaq.push(["_trackPageview",selectedOptions.join("-")]);a=getModifiedKeywords(a);b=getWrappedKeywords(a);$("#wrapper .input .summary").html(a.length+" Keywords in Total");$("#wrapper .output .summary").html(b.length+" Keywords in Total");$("#wrapper .keywords-compiled").val(b.join("\n"))}
function typoKeywords(){console.log("typoKeywords");var a=$("#typoer .keywords-input").val(),b=[];selectedOptions=[];$("#typoer .btn.active").each(function(){selectedOptions.push($(this).attr("rel"))});a=getModifiedKeywords(a);b=getGeneratedKeywords(a);$("#typoer .input .summary").html(a.length+" Keywords in Total");$("#typoer .output .summary").html(b.length+" Keywords in Total");$("#typoer .keywords-compiled").val(b.join("\n"))}
function getModifiedKeywords(a){selectedOption("lowercase")&&(a=a.toLowerCase());selectedOption("symbols")&&(a=utilDeleteExtraSymbols(a));a=a.split("\n");a=utilRemoveEmptyKeywords(a);selectedOption("duplicates")&&(a=utilRemoveDuplicates(a));return a}function getGeneratedKeywords(a){var b=[],b=[];selectedOption("disorder")&&(b=getDisorderedKeywords(a));var e=[];selectedOption("mistype")&&(e=getMistypedKeywords(a));b=a.concat(b,e);selectedOption("duplicates")&&(b=utilRemoveDuplicates(b));return b}
function getWrappedKeywords(a){var b=[];selectedOption("broad")&&(b=b.concat(getBroadKeywords(a)));selectedOption("broad-modified")&&(b=b.concat(getBroadModifiedKeywords(a)));selectedOption("phrase")&&(b=b.concat(getPhraseKeywords(a)));selectedOption("exact")&&(b=b.concat(getExactKeywords(a)));selectedOption("duplicates")&&(b=utilRemoveDuplicates(b));return b}
function getKeywordsPreparedForOutput(a){a=a.toLowerCase();a=utilDeleteExtraSymbols(a);a=a.split("\n");a=utilRemoveDuplicates(a);return a=utilRemoveEmptyKeywords(a)}function getBroadKeywords(a){return a}function getBroadModifiedKeywords(a){var b=[];$.each(a,function(a,c){var d=c.split(" ");$.each(d,function(a,b){d[a]="+"+b});b.push(d.join(" "))});return b}function getPhraseKeywords(a){var b=[];$.each(a,function(a,c){b.push('"'+c+'"')});return b}
function getExactKeywords(a){var b=[];$.each(a,function(a,c){b.push("["+c+"]")});return b}function getDisorderedKeywords(a){var b=[],e,c;$.each(a,function(a,h){b.push(h);e=h.length-1;for(charInd=0;charInd<e;charInd++)c=h.slice(0,charInd)+h.charAt(charInd+1)+h.charAt(charInd)+h.slice(charInd+2),b.push(c)});return b}
function getMistypedKeywords(a){var b=[],e,c,d;$.each(a,function(a,g){b.push(g);c=g.length;for(charInd=0;charInd<c;charInd++)try{e=mistypeVariations[g.charAt(charInd)],$.each(e,function(a,c){d=g.slice(0,charInd)+c+g.slice(charInd+1);b.push(d)})}catch(k){}});return b}
function utilDeleteExtraSymbols(a){a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,"");a=a.replace(/\n\n/gi,"\n");a=a.replace(/\s*\n/gi,"\n");var b=XRegExp("[^\\p{L}\\s\\d-]|_");a=XRegExp.replace(a,b,"","all");a=a.replace(/\t/g," ");return a=a.replace(/\s{2,}/g," ")}function utilRemoveDuplicates(a){var b=[];$.each(a,function(a,c){c=$.trim(c);-1===$.inArray(c,b)&&b.push(c)});return b}function utilRemoveEmptyKeywords(a){var b=[];$.each(a,function(a,c){""!=c&&b.push(c)});return b}
function permuteWords(a){var b=[];$.each(a,function(a,c){var d=permute(c.split(" "));$.each(d,function(a,c){b.push(c.join(" "))})});return b}
function permute(a,b){for(var e=-1,c,d,h,g=a.length,k=1,f=g+1;--f;k*=f);x=[Array(g),Array(g),Array(g),Array(g)];c=k;d=g+1;for(f=-1;++f<g;x[2][f]=f,x[1][f]=x[0][f]=c/=--d);for(h=Array(k);++e<k;)for(h[e]=Array(g),f=-1;++f<g;!--x[1][f]&&(x[1][f]=x[0][f],x[2][f]=(x[2][f]+1)%g),h[e][f]=b?x[3][f]:a[x[3][f]])for(x[3][f]=x[2][f],d=0;!d;d=!d)for(c=f;c;x[3][--c]==x[2][f]&&(x[3][f]=x[2][f]=(x[2][f]+1)%g,d=1));return h}
var mistypeVariations={a:["s"],b:["v","n"],c:["x","v"],d:["s","f"],e:["w","r"],f:["d","g"],g:["f","h"],h:["g","j"],i:["u","o"],j:["h","k"],k:["j","l"],l:["k"],m:["n"],n:["b","m"],o:["i","p"],p:["o"],q:["w"],r:["e","t"],s:["a","d"],t:["r","y"],u:["y","i"],v:["c","b"],w:["q","e"],x:["z","c"],y:["t","u"],z:["x"]," ":[" "],"-":[" "]};